# Конфиг для ai_image_processor

tasks_dir: uploads/ai_image/tasks
results_dir: uploads/ai_image/results
originals_dir: uploads/ai_image/originals
processed_dir: uploads/ai_image/processed
templates_dir: uploads/ai_image/templates
logs_dir: uploads/ai_image/logs
batch_size: 10
max_image_size: 4096
log_level: INFO
wp_api_url: "https://market.royaltyres.ru/wp-json/ai-image/v1/set-processing"
wp_api_secret: "your_secret_key"

# --- Параметры удалённого rembg ---
rembg_url: "http://127.0.0.1:80"   # Адрес nginx/reverse proxy rembg
rembg_user: "user1"                # Логин для Basic Auth
rembg_pass: "password"             # Пароль для Basic Auth 